apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: grafana
spec:
  storageClassName: standard
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: grafana
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: grafana
spec:
  volumeName: grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
